package com.example.plantify;

import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.List;

public class PlantData {
    public static List<String> getFactsOfTheDay() {
        return Arrays.asList("Pflanzen produzieren Sauerstoff – auch nachts manche!",
                "Die Monstera ist eine beliebte Zimmerpflanze aus Südamerika.",
                "Aloe Vera wird oft für Hautpflegeprodukte verwendet.",
                "Ficus-Pflanzen können die Luftqualität verbessern.",
                "Einige Pflanzen können Schädlinge auf natürliche Weise fernhalten.",
                "Kakteen speichern Wasser in ihren Stämmen für Trockenzeiten.",
                "Bambus ist die am schnellsten wachsende Pflanze der Welt.",
                "Lavendel kann beruhigend wirken und beim Einschlafen helfen.",
                "Pflanzen reagieren auf Musik – manche wachsen besser mit Klassik.",
                "Sansevieria produziert auch nachts Sauerstoff.",
                "Moos kann auf Beton und sogar auf Dächern wachsen.",
                "Tomaten gehören botanisch gesehen zu den Beeren.",
                "Pfefferminze vertreibt Ameisen und Mäuse durch ihren starken Geruch.",
                "Efeututen sind ideal für Anfänger, da sie sehr pflegeleicht sind.",
                "Kräuter wie Basilikum und Rosmarin lieben sonnige Standorte.",
                "Pflanzen kommunizieren über chemische Botenstoffe.",
                "Die Venusfliegenfalle ist eine fleischfressende Pflanze.",
                "Orchideen können bis zu 100 Jahre alt werden.",
                "Gänseblümchen schließen sich nachts und öffnen sich am Tag.",
                "Zimmerpflanzen können Stress reduzieren und die Stimmung verbessern.",
                "Palmen können in Innenräumen für ein tropisches Flair sorgen.",
                "Farnpflanzen sind über 350 Millionen Jahre alt.",
                "Spinat enthält Eisen – aber weniger als man früher dachte.",
                "Die Blätter von Bäumen reinigen die Luft von Feinstaub.",
                "Einige Pflanzenarten können in der Wüste ohne Regen überleben.",
                "Zitronenbäume tragen das ganze Jahr über Früchte.",
                "Die Wurzel eines Löwenzahns kann über 1 Meter tief reichen.",
                "Rosmarin verbessert das Gedächtnis – sagt die Volksmedizin.",
                "Tomatenpflanzen geben Geruchsstoffe ab, um sich zu schützen.",
                "Paprika enthält mehr Vitamin C als Orangen.",
                "Zamioculcas wächst sogar bei wenig Licht gut.",
                "Die Lotusblume bleibt immer sauber – Schmutz perlt ab.",
                "Sukkulenten sind ideal für Menschen, die wenig gießen wollen.",
                "Gurken bestehen zu über 95% aus Wasser.",
                "Efeu kann Wände begrünen und isolieren.",
                "Thymian wird häufig als natürliches Antibiotikum eingesetzt.",
                "Basilikum wirkt entzündungshemmend und beruhigend.",
                "Pflanzen brauchen auch im Winter gelegentlich Wasser.",
                "Der Drachenbaum filtert Benzol aus der Raumluft.",
                "Petersilie ist reich an Vitamin K.",
                "Kräuter aus dem Supermarkt leben oft nur wenige Tage.",
                "Geranien blühen bei regelmäßiger Pflege den ganzen Sommer.",
                "Die Aloe-Pflanze speichert Gel mit heilender Wirkung.",
                "Der Gummibaum war früher in vielen Büros Standard.",
                "Ein Bonsai ist keine eigene Art – sondern eine Schnitttechnik.",
                "Zimmerpflanzen können die Luftfeuchtigkeit verbessern.",
                "Eukalyptusduft hilft bei Erkältungen.",
                "Lavendel hält Motten aus dem Kleiderschrank fern.",
                "Kresse wächst schon innerhalb weniger Tage.",
                "Pflanzen passen ihre Blätter je nach Lichtverhältnissen an.");


    }

    public static List<SearchPlant> getPredefinedSearchPlants() {
        return Arrays.asList(
                new SearchPlant("Ficus", "1× pro Woche"),
                new SearchPlant("Monstera", "1× pro Woche"),
                new SearchPlant("Sukkulente", "2× pro Monat"),
                new SearchPlant("Aloe Vera", "2× pro Monat"),
                new SearchPlant("Sansevieria", "alle 2 Wochen"),
                new SearchPlant("Gummibaum", "1× pro Woche"),
                new SearchPlant("Zamioculcas", "2× pro Monat"),
                new SearchPlant("Bambus", "täglich"),
                new SearchPlant("Basilikum", "täglich"),
                new SearchPlant("Orchidee", "1× pro Woche"),
                new SearchPlant("Lavendel", "1× pro Woche"),
                new SearchPlant("Efeutute", "1× pro Woche"),
                new SearchPlant("Fensterblatt", "1× pro Woche"),
                new SearchPlant("Geranie", "2× pro Woche"),
                new SearchPlant("Kaktus", "1× im Monat"),
                new SearchPlant("Yucca", "1× pro Woche"),
                new SearchPlant("Gloxinie", "2× pro Woche"),
                new SearchPlant("Veilchen", "2× pro Woche"),
                new SearchPlant("Begonie", "2× pro Woche"),
                new SearchPlant("Chrysantheme", "2× pro Woche"),
                new SearchPlant("Palme", "1× pro Woche"),
                new SearchPlant("Amaryllis", "1× pro Woche"),
                new SearchPlant("Azalee", "täglich"),
                new SearchPlant("Hydrangea", "2× pro Woche"),
                new SearchPlant("Calla", "1× pro Woche"),
                new SearchPlant("Drachenbaum", "1× pro Woche"),
                new SearchPlant("Kräuterpflanze", "täglich"),
                new SearchPlant("Tomatenpflanze", "täglich"),
                new SearchPlant("Pfefferminze", "täglich"),
                new SearchPlant("Schnittlauch", "täglich"),
                new SearchPlant("Petersilie", "täglich"),
                new SearchPlant("Zitronenbaum", "1× pro Woche"),
                new SearchPlant("Olivenbaum", "1× pro Woche"),
                new SearchPlant("Heidekraut", "2× pro Woche"),
                new SearchPlant("Usambaraveilchen", "2× pro Woche"),
                new SearchPlant("Anthurie", "1× pro Woche"),
                new SearchPlant("Bogenhanf", "1× alle 2 Wochen"),
                new SearchPlant("Tradeskantie", "2× pro Woche"),
                new SearchPlant("Philodendron", "1× pro Woche"),
                new SearchPlant("Weihnachtsstern", "1× pro Woche"),
                new SearchPlant("Zimmerlinde", "2× pro Woche"),
                new SearchPlant("Zimmeresche", "1× pro Woche"),
                new SearchPlant("Spargelpflanze", "1× pro Woche"),
                new SearchPlant("Zitronenmelisse", "täglich"),
                new SearchPlant("Rosmarin", "alle 3 Tage"),
                new SearchPlant("Thymian", "1× pro Woche"),
                new SearchPlant("Chili", "täglich"),
                new SearchPlant("Ingwer", "alle 2 Tage"),
                new SearchPlant("Spinat", "täglich"),
                new SearchPlant("Radieschen", "täglich")
        );
    }
}
